- name: "Install package dependencies"
  become: true
  ansible.builtin.apt:
    update_cache: true
    force: true
    package:
      - git
      - unzip

- name: "Download Composer install script"
  become: true
  ansible.builtin.get_url:
    url: https://getcomposer.org/installer
    dest: /home/ansible/composer-setup.php
    mode: "0755"

- name: "Run Composer install script"
  become: true
  ansible.builtin.command:
    cmd: "php composer-setup.php --install-dir=/usr/local/bin --filename=composer"
  register: out
  changed_when: out.rc != 0

- name: "Set Composer global permissions"
  become: true
  ansible.builtin.file:
    path: /usr/local/bin/composer
    mode: a+x

- name: "Remove Composer install script"
  become: true
  ansible.builtin.file:
    path: /home/ansible/composer-setup.php
    state: absent
